
#ifndef __UART_CONFIG_H__
#define __UART_CONFIG_H__


 #define UART_BAUD_RATE               UART_BAUDRATE_9600

 #define UART_RIECEVE_ENABLE          UART_ENABLED

 #define UART_SEND_ENABLE             UART_ENABLED

 #define UART_MODE_SELECT             UART_ASYNCHRONOUS

 #define UART_CHAR_SIZE               UART_8_BITS

 #define UART_RX_INTERRUPT_ENABLE     UART_DISABLED

 #define UART_TX_INTERRUPT_ENABLE     UART_DISABLED

 #define UART_UDR_INTERRUPT_ENABLE    UART_DISABLED

 #define UART_PARITY_MODE             UART_DISABLED

 #define UART_STOP_BIT_NO             UART_1_STOP_BIT

 #define UART_CLOCK_POLARITY          UART_SAMPLE_FALLING_EDGE

#endif
