#ifndef   I2C_CFG_H
#define   I2C_CFG_H

#define OPERATION_MODE		ENABLE_MASTER_MODE

#define GENERAL_CALL_MODE	GENERAL_CALL_DEACTIVATED

#define MASTER_BIT_RATE		((uint8) 0x04)

#define INTERRUPT_MODE		INTERRUPT_DISABLED


#define SLAVE_MODE_ADDRESS		((uint8) 0x04)

#define PRESCALER_VALUE 		SET_PRESCALER_1

#endif
