
#ifndef USART_CFG_H
#define USART_CFG_H

#define USART_MODE		UART_MODE
#if USART_MODE == 	USRT_MODE
#define RTX_CLK			SYNC_TRising_RFalling
#endif
#if USART_MODE == 	UART_MODE
#define BAUD_RATE		BAUD_RATE_9600
#define DOUBLE_SPEED	DOUBLE_SPEED_DISABLE
#endif
#define ACK_MODE		POLLING_BASED
#define RTX_MODE		TRANSMIT_RECEIVE
#define CHAR_SIZE		CHAR_SIZE_8_BITS
#define PARITY_MODE		PARITY_DISABLED
#define STOPPING_BITS	ONE_STOPPING_BIT


#endif
