#ifndef    UART_CFG_H
#define    UART_CFG_H

#define CHARACTER_SIZE        CHAR_SIZE_8

#define UART_ASYNC_U2X        UART_ASYNC_U2X_DISABLE

#define UART_MODE_SELECT      ASYNC_OPERATION

#define PARITY_MODE           DISABLE_PARITY_MODE 
#define STOP_BIT_SELECT       TWO_STOP_BITS

#define CLOCK_POLARITY        DISABLE_CLK

#define BAUD_RATE_SELECT      BAUD_RATE_U2X0_9600

  
#define UART_MULTI_PROCESSOR_C0M_MODE  UART_MULTI_PROCESSOR_C0M_MODE_DISABLE




#endif