#ifndef SPI_CFG_H
#define SPI_CFG_H


#define SPI_MODE             SPI_MASTER_MODE
#define SPI_CLK_IDLE_STATE   SPI_CLK_IDLE_HIGH
#define SPI_PHASE_MODE       SPI_PHASE_SETUP_LEADING
#define SPI_DOR_STATE        SPI_DOR_LSB_FIRST

#if  SPI_MODE == SPI_MASTER_MODE	
#define SPI_GEN_CLK     SPI_FREQ_DIV_16
#endif 
#endif
