#ifndef UART_CFG_H
#define UART_CFG_H


#define UART_MODE               UART_SYNC_MODE
#define UART_CLK_POLARITY       UART_RISING_TX_FALLING_RX
#define UART_PARITY_MODE 	    UART_EVEN_PARITY_MODE
#define UART_STOP_BITS_NUMBER   UART_TWO_STOP_BIT       
#define UART_BAUD_RATE_SELECT   UART_BAUD_RATE_U2X0_9600  



#endif